### ISSUE TITLE
Data corrupting when sending whole number as int16 with digits

### ISSUE THREAD

**Issue by jeybee** [geckosio/typed-array-buffer-schema#13] opened 2022-01-20 00:54 UTC
When sending an object `{id: 62, action: 2, values: [{v: 76}]}`

with this schema:

```
const valueSchema = BufferSchema.schema('value', {
    v: { type: int16, digits: 3}
});

const actionSchema = BufferSchema.schema('action', {
    id: int16,
    action: uint8,
    values: [valueSchema],
});
```

The data arrives as `{action: 2, id: 62, values: [{v: 10.464}]}`

Even though the value of v does not have decimal places, it should arrive as "v: 76.000" at the very least.

**Comment by yandeu** [comment] 2022-01-20 01:37
Without a dot, your number would be 76000 which does not fit into an int16. Please try and use int32.

Please, if it work, add a note to the docs for other users.

**Comment by Codezilluh** [comment] 2022-01-21 13:49
Although `Int16` can store `76`, you set the `digits` to `3`. This multiplies the `76` by 1000. The new number (`76000`) is too big to fit in `Int16` so it loops around. The formula for the `Int16` loop-around is something like this: `-32768 + (76000 - 32768)` which should come up to `10,464`. That result gets divided by 1000 to be `10.464`. You are getting the expected result.

With a `digits` value of `3`, the maximum number allowed for `Int16` would be `32.767` (minimum value would be `-32.768`). I suggest you use `Int32` or lower your decimal place accuracy to `2`.

I'll edit the `readme.md` today with a description of what `digits` does.

**Comment by Codezilluh** [comment] 2022-01-21 13:52
I recommend closing this as it is not a bug.

**Closed as completed** 2022-01-29 00:55 UTC
Labels: documentation
